INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1000','10','3','Car','src/media/Car.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1001','10','3','Bike','src/media/Bike.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1002','10','3','Cycle','src/media/Cycle.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1003','10','5','Bus','src/media/Bus.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1004','10','5','Doctor Set','src/media/Doctor Set.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1005','10','2','Building Blocks','src/media/Building Blocks.jpg','backorder');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1006','5','1','Duck','src/media/Duck.jpg','backorder');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1007','5','1','Ball','src/media/Ball.jpg','outofstock');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1008','5','1','Sticks','src/media/Sticks.jpg','outofstock');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1009','5','4','Billing Set','src/media/Billing Set.jpg','backorder');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1010','15','2','Bubble car','src/media/Bubble car.jpg','backorder');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1011','15','3','Soft Bear','src/media/Soft Bear.jpg','outofstock');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1012','15','5','Paw Patrol Skie ','src/media/Paw Patrol Skie .jpg','outofstock');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1013','15','10','Smart Watch','src/media/Smart Watch.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1014','20','5','Kitchen Set','src/media/Kitchen Set.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1017','25','10','Scooter','src/media/Scooter.jpg','backorder');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1018','25','8','Robot','src/media/Robot.jpg','outofstock');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1019','25','8','Laptop Advanced','src/media/Laptop Advanced.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1020','30','4','Laptop Basic','src/media/Laptop Basic.jpg','available');
INSERT INTO TOY_DETAILS (ID,PRICE,AGE,NAME,IMAGEURL,STATUS) VALUES ('1021','35','10','Mustang','src/media/Mustang.jpg','available');
